height_bias = 3.0
hilliness = [
    [
        0.0,
        0.1,
    ],
    [
        0.2,
        0.1,
    ],
    [
        0.4,
        0.3,
    ],
    [
        0.6,
        0.3,
    ],
    [
        0.8,
        0.9,
    ],
    [
        1.0,
        1.0,
    ],
]
